name: DB-Deployment

on:
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.11'

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      #- name: Configure Databricks CLI
      #  run: |
      #    databricks configure --url ${{ vars.DATABRICKS_URL }} --token ${{ secrets.DATABRICKS_TOKEN }}

      - name: Sync the branch with Databricks workspace
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks repos list


