name: Train Classification Model on Databricks

on:
  schedule:
    - cron: "0 0 1 */1 *"  # Runs at midnight on the 1st of every month
  workflow_dispatch:  # Allows manual execution

env:
  # Note the host is an "environment variable" in the Github Environment
  # while the token is a "secret" in the Github Environment
  DATABRICKS_HOST: ${{ vars.DATABRICKS_URL }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:
  train_model:
    runs-on: ubuntu-latest
    environment: Dev  # Ensure this environment has Databricks secrets

    steps:
      #----------------------------------------------
      # Check out repository
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4
      
      #----------------------------------------------
      # Set Up 3.10 Python
      #----------------------------------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'
      
      #----------------------------------------------
      # Installing Dependencies
      #----------------------------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Set ENV Variables
        run: |
          echo "MLFLOW_ARTIFACTS_PATH=${{ vars.MLFLOW_ARTIFACTS_PATH }}" >> $GITHUB_ENV
          echo "MLFLOW_REGISTRY_URI=${{ vars.MLFLOW_REGISTRY_URI }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_URI=${{ vars.MLFLOW_TRACKING_URI }}" >> $GITHUB_ENV

      #----------------------------------------------
      # Install Databricks CLI
      #----------------------------------------------
      - name: Install Databricks CLI
        uses: ./.github/actions/db-cli-install

      #----------------------------------------------
      # Create Databricks Job
      #----------------------------------------------
      - name: Create & Run Databricks Job
        run: |
          JOB_ID=$(databricks jobs submit --json "@jobs/train_job.json" | jq -r '.job_id')
          echo "JOB_ID=$JOB_ID" >> $GITHUB_ENV

